--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t omoye94/nodeserver1 ."
      - "docker tag omoye94/nodeserver1 omoye94/nodeserver1:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push omoye94/nodeserver1:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"omoye94\" --password=\"Osareme2?\""
version: 0.1

